# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  postgres: 
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: "mypostgrespassword"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.1
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass "myredispassword"

  typesense:
    image: typesense/typesense:26.0
    ports: 
      - "8108:8108"
    command: --data-dir /data --api-key mytypesensepassword --enable-cors
    volumes:
      - typesense-data:/data


volumes:
  redis-data:
  pgdata:
  typesense-data:
