/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../routes/__root'
import { Route as PlaylistsImport } from './../routes/playlists'
import { Route as IndexImport } from './../routes/index'
import { Route as AdminIndexImport } from './../routes/admin.index'
import { Route as SearchCollectionImport } from './../routes/search.$collection'

// Create/Update Routes

const PlaylistsRoute = PlaylistsImport.update({
  path: '/playlists',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const SearchCollectionRoute = SearchCollectionImport.update({
  path: '/search/$collection',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsImport
      parentRoute: typeof rootRoute
    }
    '/search/$collection': {
      id: '/search/$collection'
      path: '/search/$collection'
      fullPath: '/search/$collection'
      preLoaderRoute: typeof SearchCollectionImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PlaylistsRoute,
  SearchCollectionRoute,
  AdminIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/playlists",
        "/search/$collection",
        "/admin/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/playlists": {
      "filePath": "playlists.tsx"
    },
    "/search/$collection": {
      "filePath": "search.$collection.tsx"
    },
    "/admin/": {
      "filePath": "admin.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
